/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_qilihui_oj_core_JudgerCore */

#ifndef _Included_com_github_qilihui_oj_core_JudgerCore
#define _Included_com_github_qilihui_oj_core_JudgerCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_qilihui_oj_core_JudgerCore
 * Method:    run
 * Signature: (Lcom/github/qilihui/oj/core/model/JudgerConfig;)Lcom/github/qilihui/oj/core/model/JudgerResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_qilihui_oj_core_JudgerCore_run
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
