/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_qilihui_oj_judge_core_JudgerCore */

#ifndef _Included_com_github_qilihui_oj_judge_core_JudgerCore
#define _Included_com_github_qilihui_oj_judge_core_JudgerCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_qilihui_oj_judge_core_JudgerCore
 * Method:    run
 * Signature: (IIJJIJILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;I[Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;II)Lcom/github/qilihui/oj/judge/core/model/JudgerResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_qilihui_oj_judge_core_JudgerCore_run
  (JNIEnv *, jobject, jint, jint, jlong, jlong, jint, jlong, jint, jstring, jstring, jstring, jstring, jobjectArray, jint, jobjectArray, jint, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
